/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:userInterface:845635:
  appc.background(230);
} //_CODE_:userInterface:845635:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:640952:
  println("pauseButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:pauseButton:640952:

public void resetButtonClicked(GButton source, GEvent event) { //_CODE_:resetButton:838627:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:resetButton:838627:

public void ffButtonClicked(GButton source, GEvent event) { //_CODE_:fastForwardButton:742662:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:fastForwardButton:742662:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  userInterface = GWindow.getWindow(this, "Window title", 0, 0, 400, 800, JAVA2D);
  userInterface.noLoop();
  userInterface.setActionOnClose(G4P.KEEP_OPEN);
  userInterface.addDrawHandler(this, "win_draw1");
  pauseButton = new GButton(userInterface, 28, 19, 80, 30);
  pauseButton.setText("Pause");
  pauseButton.addEventHandler(this, "pauseButtonClicked");
  resetButton = new GButton(userInterface, 160, 19, 80, 30);
  resetButton.setText("Reset");
  resetButton.addEventHandler(this, "resetButtonClicked");
  fastForwardButton = new GButton(userInterface, 285, 20, 80, 30);
  fastForwardButton.setText("Fast Forward");
  fastForwardButton.addEventHandler(this, "ffButtonClicked");
  homeTeamLabel = new GLabel(userInterface, 88, 78, 80, 20);
  homeTeamLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  homeTeamLabel.setText("Home Team");
  homeTeamLabel.setOpaque(false);
  awayTeamLabel = new GLabel(userInterface, 230, 78, 80, 20);
  awayTeamLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  awayTeamLabel.setText("Away Team");
  awayTeamLabel.setOpaque(false);
  label1 = new GLabel(userInterface, 200, 62, 8, 286);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("| | | | | | | | | | | | | | | | | | |");
  label1.setOpaque(false);
  userInterface.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow userInterface;
GButton pauseButton; 
GButton resetButton; 
GButton fastForwardButton; 
GLabel homeTeamLabel; 
GLabel awayTeamLabel; 
GLabel label1; 
